FROM rocker/shiny:4.3.2

# Install system dependencies (if any)
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git libxml2-dev libmagick++-dev libglpk40>=5 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /srv/shiny-server

# Install your package
RUN R -e 'install.packages(c("devtools"))'
RUN R -e 'install.packages(c("ggplot2", "bsicons", "DT", "shinyjs", "shinyFiles", "shinydisconnect", "devtools"))'
# RUN R -e 'install.packages(c("Seurat", "devtools"))'
RUN R -e 'remotes::install_github("daattali/shinycssloaders")'
RUN R -e 'remotes::install_github("JohnCoene/shinyscroll")'
RUN R -e "devtools::install_github('immunogenomics/presto')"
RUN R -e 'install.packages(c("R.utils"))'

RUN rm -rf /srv/shiny-server/*
COPY /. /srv/shiny-server/
RUN rm -rf /srv/shiny-server/app_cache

RUN R -e "devtools::install('/srv/shiny-server/')"

USER shiny

EXPOSE 3838

CMD ["/usr/bin/shiny-server"]